name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, llvm-tools-preview

      - uses: jdx/mise-action@v2

      - name: Setup
        run: mise run setup

      - name: Build
        run: mise run build

      - name: Lint
        run: mise run lint

      - name: Test
        run: mise run test

      - name: Coverage
        run: mise run coverage
